# $FreeBSD: head/textproc/php73-wddx/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php74

PKGNAMESUFFIX=	-wddx

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
