PORTNAME=	apprise
PORTVERSION=	1.7.6
CATEGORIES=	net python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	nick@bunbun.be
COMMENT=	Push notifications that work with just about every platform!
WWW=		https://pypi.org/project/apprise/

LICENSE=	BSD
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python:3.9
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
